# Generated by Django 5.0.2 on 2024-07-04 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantasy', '0081_championship_sprint_fastest_lap_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greenflag_instance', to='fantasy.race')),
            ],
        ),
    ]
