# Generated by Django 4.1 on 2022-11-22 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circuitref",
                    models.CharField(db_column="circuitRef", max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Constructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "constructorref",
                    models.CharField(db_column="constructorRef", max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("round", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "circuitid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circuit",
                        to="fantasy.circuit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driverref", models.CharField(db_column="driverRef", max_length=255)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=3, null=True)),
                ("forename", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "constructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constructor",
                        to="fantasy.constructor",
                    ),
                ),
            ],
        ),
    ]
