# Generated by Django 4.1 on 2022-11-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0002_remove_race_circuitid_race_circuit_race_drivers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="drivers",
            field=models.ManyToManyField(
                null=True, related_name="attended_races", to="fantasy.driver"
            ),
        ),
    ]
