# Generated by Django 4.1 on 2022-11-22 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fantasy", "0004_remove_circuit_circuitref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="users",
            field=models.ManyToManyField(
                null=True, related_name="races_involved", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
