# Generated by Django 4.1 on 2022-11-22 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fantasy", "0005_race_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="drivers",
            field=models.ManyToManyField(
                related_name="attended_races", to="fantasy.driver"
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="users",
            field=models.ManyToManyField(
                related_name="races_involved", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
