# Generated by Django 4.1 on 2022-11-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0010_remove_race_year_race_championship"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Season",
            new_name="Championship",
        ),
        migrations.AddField(
            model_name="team",
            name="championship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="fantasy.championship",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="championship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="races",
                to="fantasy.championship",
            ),
        ),
    ]
