# Generated by Django 4.1 on 2022-11-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0013_alter_racedrivers_grid_alter_racedrivers_qualy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racedrivers",
            name="price",
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
