# Generated by Django 4.1 on 2022-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0021_rename_unique_ref_driver_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="ref",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="circuit",
            name="ref",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="constructor",
            name="ref",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
