# Generated by Django 4.1 on 2022-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0024_alter_driver_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championship",
            name="slug",
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="circuit",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="constructor",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
