# Generated by Django 4.1 on 2022-12-04 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fantasy", "0028_alter_circuit_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="constructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drivers",
                to="fantasy.constructor",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="championship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="races",
                to="fantasy.championship",
            ),
        ),
        migrations.AlterField(
            model_name="race",
            name="circuit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grand_prix",
                to="fantasy.circuit",
            ),
        ),
        migrations.AlterField(
            model_name="racedrivers",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="race_instances",
                to="fantasy.driver",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
