# Generated by Django 4.1 on 2022-12-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0030_alter_championship_series"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RaceDrivers",
            new_name="RaceDriver",
        ),
    ]
