# Generated by Django 4.1 on 2022-12-04 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0032_remove_race_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceteam",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_instances",
                to="fantasy.race",
            ),
        ),
        migrations.AlterField(
            model_name="raceteam",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="race_instances",
                to="fantasy.team",
            ),
        ),
    ]
