# Generated by Django 4.1 on 2022-12-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0037_raceteam_race_drivers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="race_drivers",
        ),
    ]
