# Generated by Django 4.1 on 2022-12-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0039_raceteam_driver1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raceteam",
            name="driver1",
        ),
    ]
