# Generated by Django 4.1 on 2023-01-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0042_driver_constructors_race_unique_championship_round"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="constructors",
            field=models.ManyToManyField(
                related_name="drivers", to="fantasy.championshipconstructor"
            ),
        ),
    ]
