# Generated by Django 4.1 on 2023-01-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0045_alter_racedriver_constructor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="racedriver",
            old_name="constructor",
            new_name="championship_constructor",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="constructor",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="constructors",
        ),
    ]
