# Generated by Django 4.1 on 2023-01-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0047_alter_raceteam_tactic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="name",
        ),
    ]
