# Generated by Django 4.1 on 2023-01-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0048_remove_team_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="team",
            name="unique_championship_account",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="account",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("user", "championship"), name="unique_championship_user"
            ),
        ),
    ]
