# Generated by Django 4.1 on 2023-02-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0049_remove_team_unique_championship_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
