# Generated by Django 4.1.4 on 2023-02-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0055_alter_racedriver_fastest_lap_alter_racedriver_grid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="is_fantasy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="championship",
            name="is_tahmin",
            field=models.BooleanField(default=True),
        ),
    ]
