# Generated by Django 4.1.4 on 2023-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0056_championship_is_fantasy_championship_is_tahmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="tahminable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="race",
            name="wikilink",
            field=models.URLField(blank=True),
        ),
    ]
