# Generated by Django 4.1.4 on 2023-03-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0058_remove_race_tahminable"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="price_img",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
