# Generated by Django 4.1.4 on 2023-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0062_race_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructor',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='race',
            name='price_img',
        ),
        migrations.AddField(
            model_name='championship',
            name='price_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
