# Generated by Django 4.1.4 on 2023-05-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0063_remove_constructor_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racedriver',
            name='sprint_fastest_lap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='racedriver',
            constraint=models.UniqueConstraint(fields=('race', 'driver'), name='unique_racedriver'),
        ),
    ]
