# Generated by Django 4.1.4 on 2023-05-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0067_alter_championshipconstructor_alternative_fontcolor'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='championshipconstructor',
            constraint=models.UniqueConstraint(fields=('championship', 'constructor'), name='unique_championship_constructor'),
        ),
        migrations.AddConstraint(
            model_name='championshipconstructor',
            constraint=models.UniqueConstraint(fields=('championship', 'garage_order'), name='unique_championship_garage_order'),
        ),
    ]
