# Generated by Django 4.1.4 on 2023-05-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0068_championshipconstructor_unique_championship_constructor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='circuit',
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
    ]
