# Generated by Django 4.1.4 on 2023-05-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0069_remove_race_circuit_delete_circuit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racedriver',
            options={'ordering': ['race__championship__series', 'race__championship__year', 'race__round', 'championship_constructor__garage_order', 'driver__number']},
        ),
        migrations.AddField(
            model_name='championship',
            name='fastest_lap_point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='fastest_lap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='sprint_fastest_lap',
            field=models.BooleanField(default=False),
        ),
    ]
