# Generated by Django 4.1.4 on 2023-05-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0070_alter_racedriver_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['-year', 'series']},
        ),
        migrations.AlterModelOptions(
            name='championshipconstructor',
            options={'ordering': ['championship', 'garage_order']},
        ),
        migrations.AlterModelOptions(
            name='constructor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['forename', 'surname']},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelOptions(
            name='racedriver',
            options={'ordering': ['race', 'championship_constructor', 'driver__number']},
        ),
        migrations.AlterModelOptions(
            name='raceteam',
            options={'ordering': ['race', 'team__user']},
        ),
        migrations.AlterModelOptions(
            name='raceteamdriver',
            options={'ordering': ['racedriver__race', 'raceteam__team__user__first_name', '-racedriver__price']},
        ),
        migrations.AddConstraint(
            model_name='championship',
            constraint=models.UniqueConstraint(fields=('year', 'series'), name='unique_year_series'),
        ),
        migrations.AddConstraint(
            model_name='raceteamdriver',
            constraint=models.UniqueConstraint(fields=('raceteam', 'racedriver'), name='unique_raceteam_racedriver'),
        ),
    ]
