# Generated by Django 4.1.4 on 2023-10-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0072_raceteam_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='deadline',
            new_name='fp1_datetime',
        ),
    ]
