# Generated by Django 4.1.4 on 2023-10-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0073_rename_deadline_race_fp1_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='fantasy_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='fp2_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='fp3_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='quali_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='sprint_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='sprint_shootout_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
