# Generated by Django 4.1.4 on 2023-10-09 08:46

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0074_race_fantasy_ready_race_fp2_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='race',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='races', to='fantasy.circuit'),
        ),
    ]
