# Generated by Django 4.1.4 on 2023-11-11 12:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0076_alter_raceteam_options_alter_raceteamdriver_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructor',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='constructor',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
