# Generated by Django 5.0.2 on 2024-02-08 15:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0079_driver_country_driver_dob_driver_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championshipconstructor',
            name='alternative_bgcolor',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='championshipconstructor',
            name='alternative_fontcolor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='championshipconstructor',
            name='bgcolor',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='championshipconstructor',
            name='fontcolor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
