# Generated by Django 5.0.2 on 2024-10-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0081_championship_sprint_fastest_lap_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='fastest_lap_point_threshold',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='championship',
            name='is_feature_overtake_point',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='championship',
            name='is_sprint_overtake_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='championship',
            name='sprint_fastest_lap_point_threshold',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
