# Generated by Django 5.0.2 on 2024-12-03 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0083_racedriver_q1_racedriver_q2_racedriver_q3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racedriver",
            name="q1",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid qualifying time format (e.g., '1:21.072' or leave it blank).",
                        regex="^(?:\\d{1,2}:\\d{2}\\.\\d{1,3})?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="q2",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid qualifying time format (e.g., '1:21.072' or leave it blank).",
                        regex="^(?:\\d{1,2}:\\d{2}\\.\\d{1,3})?$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="q3",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid qualifying time format (e.g., '1:21.072' or leave it blank).",
                        regex="^(?:\\d{1,2}:\\d{2}\\.\\d{1,3})?$",
                    )
                ],
            ),
        ),
    ]
