# Generated by Django 5.0.2 on 2024-12-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0085_alter_racedriver_q1_alter_racedriver_q2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="championship",
            name="pole_point",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
