# Generated by Django 5.1.6 on 2025-06-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0087_championship_qualy_fantasy_h2h_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='price_img',
        ),
    ]
