name: formula1turkiye

services:
  django_app:
    build:
      context: .
    image: formula1turkiye
    container_name: formula1turkiye_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
