name: ${PROJECT_SLUG}

services:
  django_app:
    build:
      context: .
    image: ${PROJECT_SLUG}
    container_name: ${PROJECT_SLUG}_container
    ports:
      - "${PROJECT_PORT_NUMBER}:8888"
    volumes:
      - .:/app
    restart: unless-stopped
