# Generated by Django 5.1.6 on 2025-03-09 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driver_ranks", "0001_initial"),
        ("fantasy", "0086_championship_pole_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollresponse",
            name="championship",
            field=models.ForeignKey(
                default=83,
                on_delete=django.db.models.deletion.CASCADE,
                to="fantasy.championship",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pollresponse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
