# Generated by Django 4.1 on 2022-11-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="race", name="circuitid",),
        migrations.AddField(
            model_name="race",
            name="circuit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grand_prix",
                to="fantasy.circuit",
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="drivers",
            field=models.ManyToManyField(
                related_name="attended_races", to="fantasy.circuit"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="constructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drivers",
                to="fantasy.constructor",
            ),
        ),
    ]
