# Generated by Django 4.1 on 2022-11-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0006_alter_race_drivers_alter_race_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceDrivers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fantasy.driver"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name='race',
            name='drivers',
        ),
        migrations.AddField(
            model_name='race',
            name='drivers',
            field=models.ManyToManyField(related_name='attended_races', through='fantasy.RaceDrivers', to='fantasy.driver'),
        ),
        migrations.AddField(
            model_name="racedrivers",
            name="race",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fantasy.race"
            ),
        ),
    ]
