# Generated by Django 4.1 on 2022-11-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0008_season_series_team_raceteam"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Series",
        ),
        migrations.AddField(
            model_name="season",
            name="series",
            field=models.CharField(default="Formula 1", max_length=255),
            preserve_default=False,
        ),
    ]
