# Generated by Django 4.1 on 2022-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0012_racedrivers_grid_racedrivers_qualy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racedrivers",
            name="grid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedrivers",
            name="qualy",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedrivers",
            name="result",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
