# Generated by Django 4.1 on 2022-11-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0014_alter_racedrivers_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="race_drivers",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="fantasy.racedrivers"
            ),
        ),
    ]
