# Generated by Django 4.1 on 2022-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0016_alter_racedrivers_driver_alter_racedrivers_race"),
    ]

    operations = [
        migrations.AddField(
            model_name="racedrivers",
            name="discount",
            field=models.BooleanField(default=False),
        ),
    ]
