# Generated by Django 4.1 on 2022-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0017_racedrivers_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="racedrivers",
            name="fastest_lap",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="racedrivers",
            name="sprint",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
