# Generated by Django 4.1 on 2022-12-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0020_alter_driver_unique_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="unique_ref",
            new_name="ref",
        ),
    ]
