# Generated by Django 4.1 on 2022-12-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fantasy",
            "0023_rename_ref_championship_slug_rename_ref_circuit_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="slug",
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
