# Generated by Django 4.1 on 2022-12-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0029_alter_driver_constructor_alter_race_championship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championship",
            name="series",
            field=models.CharField(
                choices=[
                    ("Formula 1", "Formula 1"),
                    ("Formula 2", "Formula 2"),
                    ("Formula E", "Formula E"),
                ],
                max_length=255,
            ),
        ),
    ]
