# Generated by Django 4.1 on 2022-12-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0031_rename_racedrivers_racedriver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="users",
        ),
    ]
