# Generated by Django 4.1 on 2022-12-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0034_race_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructor",
            name="championship",
            field=models.ManyToManyField(
                related_name="constructors", to="fantasy.championship"
            ),
        ),
    ]
