# Generated by Django 4.1 on 2022-12-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0035_constructor_championship"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChampionshipConstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("garage_order", models.IntegerField()),
                (
                    "championship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="constructor_instances",
                        to="fantasy.championship",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="constructor",
            name="championship",
        ),
        migrations.AddField(
            model_name="constructor",
            name="championship",
            field=models.ManyToManyField(
                related_name="constructors",
                through="fantasy.ChampionshipConstructor",
                to="fantasy.championship",
            ),
        ),
        migrations.AddField(
            model_name="championshipconstructor",
            name="constructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="championship_instances",
                to="fantasy.constructor",
            ),
        ),
    ]
