# Generated by Django 4.1 on 2022-12-16 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0038_remove_team_race_drivers"),
    ]

    operations = [
        migrations.AddField(
            model_name="raceteam",
            name="driver1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="driven",
                to="fantasy.racedriver",
            ),
        ),
    ]
