# Generated by Django 4.1 on 2022-12-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0040_remove_raceteam_driver1"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceTeamDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "racedriver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raceteamdrivers",
                        to="fantasy.racedriver",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="raceteam",
            name="race_drivers"
        ),
        migrations.AddField(
            model_name="raceteam",
            name="race_drivers",
            field=models.ManyToManyField(
                blank=True,
                related_name="raceteams",
                through="fantasy.RaceTeamDriver",
                to="fantasy.racedriver",
            ),
        ),
        migrations.AddField(
            model_name="raceteamdriver",
            name="raceteam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raceteamdrivers",
                to="fantasy.raceteam",
            ),
        ),
    ]
