# Generated by Django 4.1 on 2023-01-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0043_alter_driver_constructors"),
    ]

    operations = [
        migrations.AddField(
            model_name="racedriver",
            name="constructor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="race_drivers",
                to="fantasy.constructor",
            ),
        ),
    ]
