# Generated by Django 4.1 on 2023-01-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fantasy",
            "0046_rename_constructor_racedriver_championship_constructor_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="raceteam",
            name="tactic",
            field=models.CharField(
                choices=[("G", "Geçiş"), ("S", "Sıralama"), ("F", "Finiş")],
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("account", "championship"), name="unique_championship_account"
            ),
        ),
    ]
