# Generated by Django 4.1 on 2023-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0054_racedriver_grid_sprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racedriver",
            name="fastest_lap",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="grid",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="grid_sprint",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="qualy",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="result",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="racedriver",
            name="sprint",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
