# Generated by Django 4.1.4 on 2023-03-10 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0057_race_tahminable_race_wikilink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="tahminable",
        ),
    ]
