# Generated by Django 4.1.4 on 2023-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0059_race_price_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='finish_coefficient',
            field=models.FloatField(default=1.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championship',
            name='overtake_coefficient',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championship',
            name='qualifying_coefficient',
            field=models.FloatField(default=3.2),
            preserve_default=False,
        ),
    ]
