# Generated by Django 4.1.4 on 2023-04-02 09:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0061_championship_beginning_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='country',
            field=django_countries.fields.CountryField(default='NL', max_length=2),
            preserve_default=False,
        ),
    ]
