# Generated by Django 4.1.4 on 2023-05-17 22:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0064_racedriver_sprint_fastest_lap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='championshipconstructor',
            name='bgcolor',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='championshipconstructor',
            name='fontcolor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
    ]
