# Generated by Django 4.1.4 on 2023-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tahmin", "0002_question_racequestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="point",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
