# Generated by Django 4.1.4 on 2023-04-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin', '0005_question_choice_d_question_point_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
    ]
