# Generated by Django 4.1.4 on 2023-05-27 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0069_remove_race_circuit_delete_circuit'),
        ('tahmin', '0008_rename_racetahmin_tahmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahmin',
            name='team',
        ),
        migrations.AlterField(
            model_name='tahmin',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tahmins', to='fantasy.race'),
        ),
        migrations.DeleteModel(
            name='TahminTeam',
        ),
    ]
