# Generated by Django 5.0.2 on 2024-02-22 16:50

import colorfield.fields
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('series', models.CharField(choices=[('f1', 'Formula 1'), ('f2', 'Formula 2'), ('fe', 'Formula E')], max_length=255)),
                ('fastest_lap_point', models.PositiveSmallIntegerField(default=0)),
                ('sprint_fastest_lap_point', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-year', 'series'],
            },
        ),
        migrations.CreateModel(
            name='ChampionshipConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_order', models.IntegerField()),
                ('bgcolor', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None)),
                ('fontcolor', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
                ('alternative_bgcolor', colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=25, samples=None)),
                ('alternative_fontcolor', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'ordering': ['championship', 'garage_order'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=3, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['forename', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('round', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('datetime', models.DateTimeField()),
                ('fp1_datetime', models.DateTimeField(blank=True, null=True)),
                ('fp2_datetime', models.DateTimeField(blank=True, null=True)),
                ('fp3_datetime', models.DateTimeField(blank=True, null=True)),
                ('quali_datetime', models.DateTimeField(blank=True, null=True)),
                ('sprint_shootout_datetime', models.DateTimeField(blank=True, null=True)),
                ('sprint_datetime', models.DateTimeField(blank=True, null=True)),
                ('fantasy_ready', models.BooleanField(default=False)),
                ('wikilink', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='RaceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualy', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_sprint', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint', models.PositiveIntegerField(blank=True, null=True)),
                ('sprint_fastest_lap', models.BooleanField(default=False)),
                ('grid', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.PositiveIntegerField(blank=True, null=True)),
                ('fastest_lap', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['race', 'championship_constructor', 'driver__number'],
            },
        ),
        migrations.AddConstraint(
            model_name='championship',
            constraint=models.UniqueConstraint(fields=('year', 'series'), name='unique_championship_year_series'),
        ),
        migrations.AddField(
            model_name='championshipconstructor',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_instances', to='formula.championship'),
        ),
        migrations.AddField(
            model_name='constructor',
            name='championship',
            field=models.ManyToManyField(related_name='constructors', through='formula.ChampionshipConstructor', to='formula.championship'),
        ),
        migrations.AddField(
            model_name='championshipconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_instances', to='formula.constructor'),
        ),
        migrations.AddField(
            model_name='race',
            name='championship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='races', to='formula.championship'),
        ),
        migrations.AddField(
            model_name='race',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='races', to='formula.circuit'),
        ),
        migrations.AddField(
            model_name='racedriver',
            name='championship_constructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_drivers', to='formula.championshipconstructor'),
        ),
        migrations.AddField(
            model_name='racedriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='race_instances', to='formula.driver'),
        ),
        migrations.AddField(
            model_name='racedriver',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_instances', to='formula.race'),
        ),
        migrations.AddField(
            model_name='race',
            name='drivers',
            field=models.ManyToManyField(related_name='attended_races', through='formula.RaceDriver', to='formula.driver'),
        ),
        migrations.AddConstraint(
            model_name='championshipconstructor',
            constraint=models.UniqueConstraint(fields=('championship', 'constructor'), name='unique_formula_championship_constructor'),
        ),
        migrations.AddConstraint(
            model_name='championshipconstructor',
            constraint=models.UniqueConstraint(fields=('championship', 'garage_order'), name='unique_formula_championship_garage_order'),
        ),
        migrations.AddConstraint(
            model_name='racedriver',
            constraint=models.UniqueConstraint(fields=('race', 'driver'), name='unique_formula_racedriver'),
        ),
        migrations.AddConstraint(
            model_name='race',
            constraint=models.UniqueConstraint(fields=('championship', 'round'), name='unique_formula_championship_round'),
        ),
    ]
