# Generated by Django 5.0.2 on 2024-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
