# Generated by Django 5.1.6 on 2025-03-22 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0005_rating_vote_count_1_rating_vote_count_10_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="vote_count_1",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="1",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_10",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="10",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_2",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="2",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_3",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="3",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_4",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="4",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_5",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="5",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_6",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="6",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_7",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="7",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_8",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="8",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="vote_count_9",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="9",
            ),
        ),
    ]
