# Generated by Django 4.1.4 on 2023-03-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0056_championship_is_fantasy_championship_is_tahmin"),
        ("tahmin", "0003_question_answer_question_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="race",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="questions",
                to="fantasy.race",
            ),
        ),
        migrations.DeleteModel(
            name="RaceQuestion",
        ),
    ]
