# Generated by Django 4.1.4 on 2023-03-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tahmin", "0004_question_race_delete_racequestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choice_D",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="point_D",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="racetahmin",
            name="question_1",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="racetahmin",
            name="question_2",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
    ]
