# Generated by Django 4.1.4 on 2023-05-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tahmin', '0010_rename_question_1_tahmin_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['race']},
        ),
        migrations.AlterModelOptions(
            name='tahmin',
            options={'ordering': ['race', 'user__first_name']},
        ),
        migrations.AddConstraint(
            model_name='tahmin',
            constraint=models.UniqueConstraint(fields=('race', 'user'), name='unique_tahmin'),
        ),
    ]
